#!/usr/bin/env python3
"""
Generate ui_heading_digit_assets.c: RGB565 LVGL images for 0-9 and dash.
Run from repo root: python 硬件/ui/tools/gen_heading_digit_assets.py
"""
from __future__ import annotations

import os

# 5 columns x 7 rows, '.' background '#' foreground
DIGITS: dict[str, list[str]] = {
    "0": [".###.", "#...#", "#...#", "#...#", "#...#", "#...#", ".###."],
    "1": ["..#..", ".##..", "..#..", "..#..", "..#..", "..#..", ".###."],
    "2": [".###.", "#...#", "....#", "...#.", "..#..", ".#...", "#####"],
    "3": [".###.", "#...#", "....#", "..##.", "....#", "#...#", ".###."],
    "4": ["...#.", "..##.", ".#.#.", "#..#.", "#####", "...#.", "...#."],
    "5": ["#####", "#....", "####.", "....#", "....#", "#...#", ".###."],
    "6": [".###.", "#...#", "#....", "####.", "#...#", "#...#", ".###."],
    "7": ["#####", "....#", "...#.", "..#..", ".#...", ".#...", ".#..."],
    "8": [".###.", "#...#", "#...#", ".###.", "#...#", "#...#", ".###."],
    "9": [".###.", "#...#", "#...#", ".####", "....#", "#...#", ".###."],
    "-": [".....", ".....", ".....", "#####", ".....", ".....", "....."],
}


def rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def rasterize(pattern: list[str], scale: int) -> tuple[int, int, bytes]:
    rows = len(pattern)
    cols = len(pattern[0])
    w = cols * scale
    h = rows * scale
    black = rgb565(0x11, 0x11, 0x11)
    white = rgb565(0xFF, 0xFF, 0xFF)
    out = bytearray(w * h * 2)
    for py in range(h):
        row = py // scale
        for px in range(w):
            col = px // scale
            ch = pattern[row][col]
            c = black if ch == "#" else white
            i = (py * w + px) * 2
            out[i] = c & 0xFF
            out[i + 1] = (c >> 8) & 0xFF
    return w, h, bytes(out)


def c_escape(data: bytes, line_width: int = 12) -> str:
    parts: list[str] = []
    line: list[str] = []
    for i, b in enumerate(data):
        line.append(f"0x{b:02x}")
        if len(line) >= line_width:
            parts.append(", ".join(line))
            line = []
    if line:
        parts.append(", ".join(line))
    return ",\n    ".join(parts)


def main() -> None:
    # Smaller sprites keep Flash / compile time reasonable; adjust scale to taste (must re-run script).
    scale = 12
    out_path = os.path.join(os.path.dirname(__file__), "..", "ui_heading_digit_assets.c")
    out_path = os.path.normpath(out_path)

    maps: list[tuple[str, int, int, bytes]] = []
    order = [str(d) for d in range(10)] + ["-"]
    for key in order:
        w, h, raw = rasterize(DIGITS[key], scale)
        name = f"ui_heading_digit_map_{key}" if key != "-" else "ui_heading_digit_map_dash"
        maps.append((name, w, h, raw))

    w0, h0, _ = maps[0][1], maps[0][2], maps[0][3]
    for name, w, h, _ in maps:
        if w != w0 or h != h0:
            raise SystemExit(f"size mismatch {name} {w}x{h} vs {w0}x{h0}")

    blocks = []
    for name, w, h, raw in maps:
        blocks.append(
            f"static LV_ATTRIBUTE_MEM_ALIGN const uint8_t {name}[] = {{\n    {c_escape(raw)}\n}};"
        )

    body_maps = "\n\n".join(blocks)

    stride = w0 * 2  # RGB565 bytes per row
    entries = []
    names = [m[0] for m in maps]
    for name in names:
        entries.append(
            f"""    {{
        .header = {{
            .magic = LV_IMAGE_HEADER_MAGIC,
            .cf = LV_COLOR_FORMAT_RGB565,
            .flags = 0,
            .w = {w0},
            .h = {h0},
            .stride = {stride},
            .reserved_2 = 0,
        }},
        .data_size = (uint32_t)sizeof({name}),
        .data = {name},
        .reserved = NULL,
        .reserved_2 = NULL,
    }}"""
        )

    c_source = f"""/* Auto-generated by tools/gen_heading_digit_assets.py — do not edit by hand */
#include <lvgl/lvgl.h>

#if !defined(LV_ATTRIBUTE_MEM_ALIGN)
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

{body_maps}

const lv_image_dsc_t ui_heading_digit_imgs[11] = {{
{",\n".join(entries)}
}};
"""
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(c_source)
    print(f"Wrote {out_path} ({w0}x{h0} x 11 images)")


if __name__ == "__main__":
    main()
